### ISSUE TITLE
extra visio figure

### ISSUE THREAD

**Issue by kameyer226** [yaq-project/yaq-protocol-publication#10]
This is just a pointer to examine the Visio stenciling result for figure 1, limited to a bare minimum of images so that any discussion can be made as to its utility.  It is found in a separate branch, not for MRs , in a folder marked `temp_figures` .

**Comment by untzag** [comment]
I think we have consensus that the "simplified" version of the network figure made by @ksunden is preferred to the Visio style. Ultimately it's a stylistic choice---not a huge impact either way.
