### ISSUE TITLE
Comment about windows XP

### ISSUE THREAD

**Issue by ksunden** [yaq-project/yaq-protocol-publication#12]
@ddkohler pointed out that technically the versions of python supported by yaq do not run on windows XP (officially, at least).
The last supported version of python for win XP was 3.4, which was before async/await keywords, though technically probably _could_ be adapted to work... not at all worth it without a good reason, though.

The way I see it we can:

- Ignore this technicality: yaq is a protocol and just because an implementation doesn't exist yet doesn't mean it can't
- Change that to Win Vista/7, as those _are_ supported by versions of python for which yaq does work, but still gets the point across (if not quite as impactful as saying XP...)
- Come up with an alternate "strange edge case" of similar ilk

**Comment by untzag** [comment]
> Ignore this technicality: yaq is a protocol and just because an implementation doesn't exist yet doesn't mean it can't

This is my vote, and was the intended reading when we wrote this example.

I think it's fine to keep the Windows XP example when we are listing possible examples, but maybe it was a mistake to privilege that example in the exposition paragraph. I'll replace Windows XP with Raspberry Pi for exposition.
