### ISSUE TITLE
WiQK citation

### ISSUE THREAD

**Issue by ksunden** [yaq-project/yaq-protocol-publication#22]
Requested by @ddkohler 

@untzag any thoughts?

https://github.com/uw-madison-chem-shops/yaqc-wiqk is the only real thing I can point to myself

**Comment by untzag** [comment]
There is no such citation AFAIK.

Let's leave this issue open. Once we have a final draft I will contact the Landis group and ask them for permission and if they would like to add a citation.

**Comment by untzag** [comment]
I contacted Clark, asked for both permission and if cite. OK to use, no citation.
