### ISSUE TITLE
Share a full text on other platforms

### ISSUE THREAD

**Issue by kadykov** [yaq-project/yaq-protocol-publication#58]
Congratulations on a great paper!
Do you consider publishing a full text on other platforms like [arXiv](https://arxiv.org/), [viXra](https://vixra.org/) or [ResearchGate](https://www.researchgate.net/publication/369989982_The_yaq_project_Standardized_software_enabling_flexible_instrumentation)?

**Comment by untzag** [comment]
Hi @kadykov, honestly it never occurred to me. I've uploaded to ResearchGate and I'll consider arXiv. I've never heard of viXra so I'm unlikely to upload there.
